
import jsPDF from 'jspdf';
import { AnalysisHistory } from './historyUtils';

export const generateAnalysisPDF = (analysis: AnalysisHistory) => {
  const doc = new jsPDF();
  
  // Set up colors and fonts
  const primaryColor = [59, 130, 246] as const; // Blue
  const textColor = [51, 65, 85] as const; // Slate gray
  const lightGray = [248, 250, 252] as const;
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('SEHAT - SKIN ANALYSIS REPORT', 20, 30);
  
  // Horizontal line
  doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);
  
  // Analysis details
  doc.setFontSize(12);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  
  let yPosition = 50;
  
  // Date and time
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis Date:', 20, yPosition);
  doc.setFont('helvetica', 'normal');
  doc.text(`${analysis.date} at ${analysis.time}`, 60, yPosition);
  
  yPosition += 10;
  
  // Analysis ID
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis ID:', 20, yPosition);
  doc.setFont('helvetica', 'normal');
  doc.text(analysis.id, 60, yPosition);
  
  yPosition += 20;
  
  // Results section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('ANALYSIS RESULTS', 20, yPosition);
  
  yPosition += 15;
  
  // Detected condition
  doc.setFontSize(12);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Detected Condition:', 20, yPosition);
  doc.setFont('helvetica', 'normal');
  doc.text(analysis.prediction, 20, yPosition + 8);
  
  yPosition += 25;
  
  // Confidence level
  doc.setFont('helvetica', 'bold');
  doc.text('Confidence Level:', 20, yPosition);
  doc.setFont('helvetica', 'normal');
  const confidenceText = `${(analysis.confidence * 100).toFixed(1)}%`;
  doc.text(confidenceText, 20, yPosition + 8);
  
  // Confidence bar
  const barWidth = 100;
  const barHeight = 6;
  const barX = 20;
  const barY = yPosition + 15;
  
  // Background bar
  doc.setFillColor(230, 230, 230);
  doc.rect(barX, barY, barWidth, barHeight, 'F');
  
  // Confidence bar fill
  const fillWidth = barWidth * analysis.confidence;
  if (analysis.confidence >= 0.8) {
    doc.setFillColor(34, 197, 94); // Green
  } else if (analysis.confidence >= 0.6) {
    doc.setFillColor(234, 179, 8); // Yellow
  } else {
    doc.setFillColor(239, 68, 68); // Red
  }
  doc.rect(barX, barY, fillWidth, barHeight, 'F');
  
  yPosition += 35;
  
  // Extracted text if available
  if (analysis.extractedText) {
    doc.setFont('helvetica', 'bold');
    doc.text('Extracted Text:', 20, yPosition);
    doc.setFont('helvetica', 'normal');
    
    // Split long text into multiple lines
    const textLines = doc.splitTextToSize(analysis.extractedText, 170);
    doc.text(textLines, 20, yPosition + 8);
    yPosition += 8 + (textLines.length * 5);
  }
  
  yPosition += 20;
  
  // Disclaimer section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('IMPORTANT DISCLAIMER', 20, yPosition);
  
  yPosition += 15;
  
  doc.setFontSize(10);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.setFont('helvetica', 'normal');
  const disclaimerText = [
    'This analysis is for educational and informational purposes only.',
    'The results should not be considered as medical advice or diagnosis.',
    'Please consult with a qualified healthcare professional for proper',
    'medical evaluation and treatment recommendations.',
    '',
    'Sehat AI is a tool designed to assist in skin condition identification',
    'but should never replace professional medical consultation.'
  ];
  
  disclaimerText.forEach((line, index) => {
    doc.text(line, 20, yPosition + (index * 5));
  });
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Sehat AI - Skin Disease Detection', 20, pageHeight - 20);
  doc.text(`Report generated on ${new Date().toLocaleDateString()}`, 20, pageHeight - 15);
  
  return doc;
};
